In [34]:
from sklearn.feature_extraction.text import CountVectorizer
import sys,os
sys.path.append(os.path.join(os.getcwd(), '..'))
from config import loc_config
import pandas as pd

data = pd.read_csv(loc_config.cyber_bully_data_path)
data

tweet_text cyberbullying_type
0      In other words #katandandre, your food was cra...  not_cyberbullying
1      Why is #aussietv so white? #MKR #theblock #ImA...  not_cyberbullying
2      @XochitlSuckkks a classy whore? Or more red ve...  not_cyberbullying
3      @Jason_Gio meh. :P  thanks for the heads up, b...  not_cyberbullying
4      @RudhoeEnglish This is an ISIS account pretend...  not_cyberbullying
...                                                  ...                ...
47687  Black ppl aren't expected to do anything, depe...          ethnicity
47688  Turner did not withhold his disappointment. Tu...          ethnicity
47689  I swear to God. This dumb nigger bitch. I have...          ethnicity
47690  Yea fuck you RT @therealexel: IF YOURE A NIGGE...          ethnicity
47691  Bro. U gotta chill RT @CHILLShrammy: Dog FUCK ...          ethnicity

[47692 rows x 2 columns]

In [35]:
import numpy as np

data['cyberbullying_type'] = np.where(data['cyberbullying_type'] == 'not_cyberbullying', 1, 0)
data

tweet_text  cyberbullying_type
0      In other words #katandandre, your food was cra...                   1
1      Why is #aussietv so white? #MKR #theblock #ImA...                   1
2      @XochitlSuckkks a classy whore? Or more red ve...                   1
3      @Jason_Gio meh. :P  thanks for the heads up, b...                   1
4      @RudhoeEnglish This is an ISIS account pretend...                   1
...                                                  ...                 ...
47687  Black ppl aren't expected to do anything, depe...                   0
47688  Turner did not withhold his disappointment. Tu...                   0
47689  I swear to God. This dumb nigger bitch. I have...                   0
47690  Yea fuck you RT @therealexel: IF YOURE A NIGGE...                   0
47691  Bro. U gotta chill RT @CHILLShrammy: Dog FUCK ...                   0

[47692 rows x 2 columns]

In [14]:
vectorizer = CountVectorizer()
x = vectorizer.fit_transform(data['tweet_text'])
print(vectorizer.get_feature_names_out())
print(x.toarray())

['00' '000' '0000841420' ... '𝕨𝕠𝕦𝕝𝕕' '𝕫𝕠𝕖𝕪' '𝚎𝚕𝚞𝚜𝚒𝚟𝚎']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
data['cyberbullying_type'].unique()

array(['1', '0'], dtype=object)

In [33]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# Transform only the sentences
X = vectorizer.transform(data['tweet_text'])
y = data['cyberbullying_type']
# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

# Train
clf = DecisionTreeClassifier(random_state=0).fit(X_train, y_train)

# Predict
y_pred = clf.predict(X_test)

# Evaluate
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.830380543033861


In [31]:
sample_text = ['I love shoes']
sample_text_vector = vectorizer.transform(sample_text)
print(clf.predict(sample_text_vector))

sample_text = ['Send me money immediately bloddy fool and idiot.']
sample_text_vector = vectorizer.transform(sample_text)
print(clf.predict(sample_text_vector))

sample_text = ['You are a good person']
sample_text_vector = vectorizer.transform(sample_text)
print(clf.predict(sample_text_vector))

['1']
['0']
['0']
